
-
  name: 'Freeveggie - Blog post pagination default'
  uriPattern:    '{node}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--posts-paginator':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
      'currentPage': '1'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: true

-
  name: 'Freeveggie - Blog post pagination - page > 1'
  uriPattern:    '{node}/page/{--posts-paginator.currentPage}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--posts-paginator':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: true
