TYPO3:
  TYPO3CR:
    contentDimensions:
      'language':
        default: 'de'
        defaultPreset: 'de'
        presets:
          'all': ~
          'de':
            label: 'German'
            values: ['de', 'en']
            uriSegment: 'de'
          'en':
            label: 'English'
            values: ['en', 'de']
            uriSegment: 'en'
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'print'
          title: 'Print'
          position: 200
      requireJsPathMapping:
        'FreeVeggie.Blog/Inspector/Editors': 'resource://FreeVeggie.Blog/Public/JavaScript/Content/Inspector/Editors/'
      inspector:
        dataTypes:
          'ingredients':
            editor: 'FreeVeggie.Blog/Inspector/Editors/IngredientsEditor'
    nodeTypes:
      groups:
        freeveggie:
          position: 'after general'
          label: 'Free veggie'
    typoScript:
      autoInclude:
        'FreeVeggie.Blog': true