TYPO3:
  Flow:
    i18n:
      defaultLocale: de
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            matchingStatusCodes: [ 404 ]
            options:
              templatePathAndFilename: 'resource://FreeVeggie.Blog/Private/Templates/Error/Index.html'
              format: 'html'

  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: FALSE
          isPreviewMode: TRUE
          typoScriptRenderingPath: 'print'
          title: 'Print'
          position: 200
      requireJsPathMapping:
        'FreeVeggie.Blog/Inspector/Editors': 'resource://FreeVeggie.Blog/Public/JavaScript/Content/Inspector/Editors/'
      inspector:
        dataTypes:
          'ingredients':
            editor: 'FreeVeggie.Blog/Inspector/Editors/IngredientsEditor'
    nodeTypes:
      groups:
        freeveggie:
          position: 'after general'
          label: 'Free Veggie'
        freeveggiecontent:
          position: 'after general'
          label: 'Free Veggie: Content'
        freeveggiemenu:
          position: 'after freeveggiecontent'
          label: 'Free Veggie: Menu'
        freeveggiecarousel:
          position: 'after freeveggiemenu'
          label: 'Free Veggie: Carousel'
    typoScript:
      autoInclude:
        'FreeVeggie.Blog': true